name: Node.js CI

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # The OS to run the workflow on

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Replace with your Node.js version

      # Install dependencies
      - name: Install dependencies
        run: npm install


      # Optionally, build the project (for production)
      - name: Build project
        run: npm run build
